export const SET_SESION_LOADED = 'alegaciones/auth/SET_SESION_LOADED'
export const SET_IS_FETCHING = 'alegaciones/auth/SET_IS_FETCHING'
export const SET_TOKEN = 'alegaciones/auth/SET_TOKEN'
export const SET_EMAIL = 'alegaciones/auth/SET_EMAIL'
export const SET_NAME = 'alegaciones/auth/SET_NAME'
export const SET_ROL = 'alegaciones/auth/SET_ROL'
export const LOG_OUT = 'alegaciones/auth/LOG_OUT'
